INSERT INTO juegos (nombre_juego, jugadores_juego, edad_juego) 
VALUES 
('7 Wonder Duel Agora', '2', '10+'),
('7 Wonders Duel', '2', '10+'),
('7 Wonders Duel Panteon', '2', '10+'),
('Agricola Edición Aniversario', '1-4', '12+'),
('Anda a lavar', '2-8', '8+'),
('Arte Moderno', '3-5', '10+'),
('Azul Master Chocolatier', '2-4', '8+'),
('Beez', '2-4', '8+'),
('Bohnanza', '3-5', '10+'),
('Boon Lake', '1-4', '14+'),
('Brain box Harry Potter', '1+', '8+'),
('Break the Code', '2-4', '10+'),
('Bubble Stories', '1-2', '+4'),
('Carcassonne base', '2-5', '7+'),
('Carcassonne big box', '2-6', '7+'),
('Catan Edicion de Viaje', '2-4', '10+'),
('Catan El Juego', '3-4', '10+'),
('Clue', '2-6', '8+'),
('Codigo Secreto Duo ', '2', '11+'),
('Con eso no se jode', '3-10', '18+'),
('Corruptia segunda vuelta', '2', '14+'),
('Cortex challenge', '2-6', '6+'),
('Crop circle', '1-12', '8+'),
('Cthuthu Deadh May Die', '1-5', '14+'),
('Dixit Base', '3-8', '8+'),
('Dixit Daydreams', '3-8', '8+'),
('Dobble Clasico', '2-8', '7+'),
('Dobble Harry Potter', '2-8', '7+'),
('Donde las papas queman', '2-6', '8+'),
('El Dilema del Rey', '3-5', '14+'),
('El Monstruo de Colores', '2-5', '3+'),
('Ensalada de puntos ', '2-6', '8+'),
('Exploding Kittens', '2-5', '7+'),
('Fantasma Blitz', '2-8', '8+'),
('Fast food fear', '3-6', '8+'),
('Globe Twister', '1-5', '8+'),
('Granjeros', '4-5', '12+'),
('Happy Little Dinosaurs', '2-4', '8+'),
('Happy Little Dinosaurs Citas desastrosas', '2-4', '8+'),
('Happy Little Dinosaurs Los Peligros de la pubertad', '2-4', '8+'),
('Hogar dulce hogar o no ', '2-5', '8+'),
('Imploding Kittengs', '2-5', '7+'),
('IQ Files pecados', '1-6', '14+'),
('Ishtar', '2-4', '14+'),
('King of New York', '2-6', '10+'),
('King of Tokio', '2-6', '10+'),
('La Isla Prohibida', '2-4', '10+'),
('Las Brujas de Cernegula', '2-4', '+10'),
('Legado Perdido: El Grial Sagrado y el Baculo de Dragones', '2-4', '+10'),
('Legado Perdido: La Espada Vorpal y el Chapitel de Electro', '2-4', '+10'),
('Legado Perdido: La Nave y el Jardin Flotante', '2-4', '+10'),
('Llama', '2-6', '8+'),
('Los 7 odiosos', '2-6', '8+'),
('Los Castillos de Borgoña', '1-4', '12+'),
('Luna Capital', '1-4', '8+'),
('Mada', '2-5', '6+'),
('Mal trago', '4-10', '8+'),
('Mariposas', '2-5', '14+'),
('Mazescape Ariadne', '1', '8+'),
('Mazescape Cryo-C', '1', '8+'),
('Mazescape Kids Hypnos', '1', '8+'),
('Mazescape Labyrinthos', '1', '8+'),
('Messina 1347', '1-4', '12+'),
('Mindbug', '2', '8+'),
('Monkeelaus', '1-5', '8+'),
('Monopoly Base', '2-6', '8+'),
('Monopoly Mario Car', '2-4', '8+'),
('My City', '2-4', '10+'),
('Oso Park', '2-4', '8+'),
('Pandemic', '2-4', '8+'),
('Paris La Cité de la Lumiere', '2', '8+'),
('Patchwork', '2', '8+'),
('Patzcuaro', '2-4', '8+'),
('Polilla tramposa', '3-5', '7+'),
('Regicide', '1-4', '10+'),
('Regine', '2-4', '10+'),
('Revolucion 1828', '2', '12+'),
('Sand', '1-4', '14+'),
('Sanssouci', '2-4', '8+'),
('Scout', '2-5', '9+'),
('Scrabble', '2-4', '12+'),
('Silk', '2-4', '10+'),
('Simplicity', '2-6', '10+'),
('Skull King', '2-8', '8+'),
('Sonora', '1-4', '10+'),
('Stranger Things Mundo del reves', '2-4', '12+'),
('Sushi go', '2-5', '8+'),
('Terraforming Mars', '1-5', '12+'),
('The game', '1-5', '8+'),
('The Island', '2-4', '8+'),
('The mind', '2-4', '8+'),
('The Red Cathedral', '1-4', '10+'),
('3 Ring Circus', '1-4', '12+'),
('Ticket to Ride Amsterdam', '2-4', '8+'),
('Ticket to Ride Europa', '2-5', '8+'),
('Time Line Eventos', '2-6', '8+'),
('Tzolk-in', '2-4', '13+'),
('Unlock scape adventures', '1-6', '10+'),
('Veggies', '2-4', '8+'),
('Virus 2', '2-6', '8+'),
('Virus base', '2-6', '8+'),
('Wingspan', '1-5', '10+'),
('Winter 4 Temporada', '2', '8+'),
('Winter Kingdom', '2-4', '14+'),
('Wyrmspan', '2-4', '14+');
